=pod

=head1 NAME

WWW::Mechanize::Firefox::Installation - How to install the components

=head1 Installation

If you notice that tests get skipped and/or the module installs
but "does not seem to work", there are some more steps required
to configure Firefox:

If tests fail with an error from Firefox that a file could not
be found, check that the test suite and the Firefox process are
run using the same user. Otherwise, the Firefox process might not
have the permissions to access the files created by the test suite.

=head1 SEE ALSO

L<https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Developer_setup>

=head1 PPMs

If you use ActiveStates package manager, you can find
some pre-packaged but untested PPMs at
L<https://github.com/Corion/www-mechanize-firefox/downloads> .

As I don't use C<ppm>, I can't offer any support for them.

=head1 AUTHOR

Max Maischein C<corion@cpan.org>

=head1 COPYRIGHT

Copyright 2010-2014 by Max Maischein C<corion@cpan.org>.

All Rights Reserved. This module is free software. It may be used,
redistributed and/or modified under the same terms as Perl itself.

=cut