---
abstract: 'use Firefox as if it were WWW::Mechanize'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Image::Info: '0'
  Test::Deep: '0'
  Test::HTTP::LocalServer: '0.61'
  Test::More: '0'
  URI: '0'
  URI::file: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Mechanize-Firefox
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '0'
  File::Basename: '0'
  HTML::Selector::XPath: '0'
  HTTP::Cookies: '0'
  HTTP::Date: '0'
  HTTP::Request::Common: '0'
  HTTP::Response: '0'
  MIME::Base64: '0'
  MozRepl::RemoteObject: '0.39'
  Object::Import: '0'
  Scalar::Util: '1.14'
  Shell::Command: '0'
  URI: '0'
  URI::data: '0'
  WWW::Mechanize: '0'
  WWW::Mechanize::Link: '0'
  parent: '0'
  perl: '5.006'
resources:
  repository: git://github.com/Corion/www-mechanize-firefox.git
version: '0.80'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
